name: redteam-lab
services:
  attacker:
    build: ./attacker
    image: redteam-lab-attacker
    container_name: redteam-lab-attacker
    cap_add: [NET_RAW, NET_ADMIN]
    volumes:
      - redteam-loot:/root/loot
      - redteam-wifi:/root/wifi
    networks:
      redteam-lab-net:
        ipv4_address: 172.28.0.5
    command: ["sleep", "infinity"]

networks:
  redteam-lab-net:
    name: redteam-lab-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  redteam-loot:
  redteam-wifi:
